name: AutoUpdate

on:
  # 毎週金曜日19時30分に実行(台湾時間)
  schedule:
    - cron: '30 11 * * 5'
  ## 手動実行用
  workflow_dispatch:

# ジョブ設定
jobs:
  AutoUpdateJob:
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - name: Checkout
        uses: actions/checkout@v3
      # Pythonインストール
      - name: Set up Python
        uses: actions/setup-python@v4
      # pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencc
      # ConvertEssay.py実行
      - name: Run ConvertEssay.py
        run: python dict_tools/ConvertEssay.py
      # ConvertMcBopomofo.py実行
      - name: Run ConvertMcBopomofo.py
        run: python dict_tools/ConvertMcBopomofo.py
      # ConvertOpenccEmoji.py実行
      - name: Run ConvertOpenccEmoji.py
        run: python dict_tools/ConvertOpenccEmoji.py
      # ConvertOpenccTwPhase.py実行
      - name: Run ConvertOpenccTwPhase.py
        run: python dict_tools/ConvertOpenccTwPhase.py
      # ファイル移動
      - name: Move files
        run: |
          mv emoji_category_tongpin.txt opencc/
          mv emoji_word_tongpin.txt opencc/
          mv TWPhrasesIT_tongpin.txt opencc/
          mv TWPhrasesName_tongpin.txt opencc/
          mv TWPhrasesOther_tongpin.txt opencc/
      # ゴミファイル削除
      - name: Remove trash files
        run: rm -rf cedict_1_0_ts_utf-8_mdbg.zip cedict_ts.u8 BPMFBase.txt BPMFMappings.txt phrase.occ TWPhrasesIT.txt.orig TWPhrasesName.txt.orig TWPhrasesOther.txt.orig emoji_category.txt.orig emoji_word.txt.orig dict_tools/__pycache__/
      # プッシュ
      - name: Push
        run: |
          git config user.name  "actions-user"
          git config user.email "action@github.com"
          git add essay_tongpin.txt tongpin.McBopomofo.dict.yaml opencc/emoji_category_tongpin.txt opencc/emoji_word_tongpin.txt opencc/TWPhrasesIT_tongpin.txt opencc/TWPhrasesName_tongpin.txt opencc/TWPhrasesOther_tongpin.txt
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto Update"
            git push origin master
          fi
